### ISSUE TITLE
[Feature] to copy cordova www files

### ISSUE THREAD

**Issue by marcusbesjes** [vigour-io/cordova-builder#2]
we need to serve cordova's `www` files to our native app, these files are in:
iOS:
`cordova-tester/.native/cordova-vanilla/platforms/ios/www`
Android:
`cordova-tester/.native/cordova-vanilla/platforms/android/platform_www`

It would be a nice feature to copy these files over to a custom destination every time we run `vigour build`

**Comment by marcusbesjes** [comment]
@tvervest what do you think?

**Comment by tvervest** [comment]
This was already in place for the MTV app, but I've removed it as we loaded the CDN root directly into the `config.xml`.

Having said that, I suggest we make a standardised pre-loader page, which does a network check and can show an offline page, or redirect to the CDN root. This way we can customise it using the config file and we won't ever have to worry about it again.
